//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareDev.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Español {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Español() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WareDev.Resources.Español", typeof(Español).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string btnInicio {
            get {
                return ResourceManager.GetString("btnInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string buthelp {
            get {
                return ResourceManager.GetString("buthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar .
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres cambiar el correo ?.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        internal static string Lenguaje {
            get {
                return ResourceManager.GetString("Lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
    }
}
